### ISSUE TITLE
Nodejs update from v12

### ISSUE THREAD

**Issue by lazysoundsystem** [mathiasvr/command-output#2]
Just noticed that this runs ['using: node12'](https://github.com/mathiasvr/command-output/blob/47cf7afef61464e8e858237a59f5a888afd2afe8/action.yml#L17) which is only maintained until the end of this month (April 2022): https://nodejs.org/en/about/releases/

This might require updating some of the dependencies, e.g. https://github.com/mathiasvr/command-output/blob/47cf7afef61464e8e858237a59f5a888afd2afe8/package-lock.json#L980

**Comment by cafuego** [comment]
Thanks @lazysoundsystem! I've fixed this for our projects and that fix is present in https://github.com/mathiasvr/command-output/pull/5
