### ISSUE TITLE
An output that contains stdout and stderr (in order)

### ISSUE THREAD

**Issue by sgielen** [mathiasvr/command-output#3]
If a command outputs something like:

```
(stdout) Running test: foo
(stderr) test failed
(stdout) Running test: bar
```

The outputs are:

stdout
```
Running test: foo
Running test: bar
```

stderr
```
test failed
```

And you wouldn't know which test failed. Would it be possible to have a second output `output` that contains both stdout and stderr, in the correct order?

Thanks!

**Comment by mathiasvr** [comment]
You can redirect stderr to stdout by adding `2>&1` to the command.

**Comment by sgielen** [comment]
That requires changing the original step, though, which may be a longer `run` script.

Although I suppose you could just add an `exec 2>&1` at the top, so now that I think about it, it isn't as bad as I thought. I'll go with that :-)

Thanks for taking the time to get back to me!
