### ISSUE TITLE
Generates warning about set-output command being deprecated

### ISSUE THREAD

**Issue by scouten-adobe** [mathiasvr/command-output#4]
I used this action in a [recent workflow](https://github.com/adobe/xmp-toolkit-rs/actions/runs/3291504965/jobs/5425744060#step:6:13) and it generated a warning:

> Warning: The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by cafuego** [comment]
The fix *should* be to simply bump @actions/core to v1.10.0 as per https://github.com/mathiasvr/command-output/pull/5

**Comment by CassieSloan** [comment]
bump - this would've been really useful if it worked with new github actions

**Comment by debek** [comment]
@mathiasvr can you bump?
